variables:
  LC_ALL: C.UTF-8

stages:
  - test

test:python2:pep8:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-pep8.sh /tmp
    - PYTHON=python2 /tmp/compare-pep8.sh
  tags:
    - docker
    - linux
    - amd64

test:python2:pylint:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-pylint.sh /tmp
    - PYTHON=python2 /tmp/compare-pylint.sh
  artifacts:
    when: on_failure
    expire_in: '1 hour'
    paths:
      - base.log
      - head.log
  tags:
    - docker
    - linux
    - amd64

test:python2:comparative:kresd:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-tests.sh /tmp
    - PYTHON=python2 /tmp/compare-tests.sh $(pwd)/kresd_run.sh
  artifacts:
    when: always
    expire_in: '1 hour'
    paths:
      - modified_tests
      - base.log
      - base.tests
      - head.log
      - head.tests
  tags:
    - docker
    - linux
    - amd64

test:python3:pep8:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-pep8.sh /tmp
    - PYTHON=python3 /tmp/compare-pep8.sh
  tags:
    - docker
    - linux
    - amd64

test:python3:pylint:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-pylint.sh /tmp
    - PYTHON=python3 /tmp/compare-pylint.sh
  artifacts:
    when: on_failure
    expire_in: '1 hour'
    paths:
      - base.log
      - head.log
  tags:
    - docker
    - linux
    - amd64

test:python3:comparative:kresd:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-tests.sh /tmp
    - PYTHON=python3 /tmp/compare-tests.sh $(pwd)/kresd_run.sh
  artifacts:
    when: always
    expire_in: '1 hour'
    paths:
      - modified_tests
      - base.log
      - base.tests
      - head.log
      - head.tests
  tags:
    - docker
    - linux
    - amd64

# Run all tests on the latest kresd version to ensure that we not push tests
# which do not work on latest kresd. It would lead to breakage in kresd CI.
test:python3:latest:kresd:
  image: cznic/deckard-ci
  stage: test
  script:
    - git clone --depth=1 https://gitlab.labs.nic.cz/knot/resolver.git kresd-local-build
    - GIT_DIR=$(pwd)/kresd-local-build/.git git log -1
    - PREFIX=$(pwd)/.local make -C kresd-local-build -k all
    - PREFIX=$(pwd)/.local make -C kresd-local-build install
    - LD_LIBRARY_PATH=$(pwd)/.local/lib DAEMON=$(pwd)/.local/sbin/kresd MAKEFLAGS="-j $(nproc) --keep-going" ./kresd_run.sh
  tags:
    - docker
    - linux
    - amd64
