variables:
  LC_ALL: C.UTF-8

stages:
  - test

test:python2:pep8:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-pep8.sh /tmp
    - PYTHON=python2 /tmp/compare-pep8.sh
  tags:
    - docker
    - linux
    - amd64

test:python2:pylint:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-pylint.sh /tmp
    - PYTHON=python2 /tmp/compare-pylint.sh
  artifacts:
    when: on_failure
    expire_in: '1 hour'
    paths:
      - base.log
      - head.log
  tags:
    - docker
    - linux
    - amd64

test:python2:comparative:kresd:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-tests.sh /tmp
    - PYTHON=python2 /tmp/compare-tests.sh $(pwd)/kresd_run.sh
  artifacts:
    when: always
    expire_in: '1 hour'
    paths:
      - modified_tests
      - base.log
      - base.tests
      - head.log
      - head.tests
  tags:
    - docker
    - linux
    - amd64

test:python3:pep8:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-pep8.sh /tmp
    - PYTHON=python3 /tmp/compare-pep8.sh
  tags:
    - docker
    - linux
    - amd64

test:python3:pylint:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-pylint.sh /tmp
    - PYTHON=python3 /tmp/compare-pylint.sh
  artifacts:
    when: on_failure
    expire_in: '1 hour'
    paths:
      - base.log
      - head.log
  tags:
    - docker
    - linux
    - amd64

test:python3:comparative:kresd:
  image: cznic/deckard-ci
  stage: test
  script:
    - cp ci/common.sh /tmp
    - cp ci/compare-tests.sh /tmp
    - PYTHON=python3 /tmp/compare-tests.sh $(pwd)/kresd_run.sh
  artifacts:
    when: always
    expire_in: '1 hour'
    paths:
      - modified_tests
      - base.log
      - base.tests
      - head.log
      - head.tests
  tags:
    - docker
    - linux
    - amd64

# Run all tests on the latest kresd version to ensure that we not push tests
# which do not work on latest kresd. It would lead to breakage in kresd CI.
test:python3:latest:kresd:
  image: cznic/deckard-ci
  stage: test
  script:
    - git clone --depth=1 https://gitlab.labs.nic.cz/knot/resolver.git kresd-local-build
    - GIT_DIR=$(pwd)/kresd-local-build/.git git log -1
    - PREFIX=$(pwd)/.local make -C kresd-local-build -k all
    - PREFIX=$(pwd)/.local make -C kresd-local-build install
    - LD_LIBRARY_PATH=$(pwd)/.local/lib DAEMON=$(pwd)/.local/sbin/kresd MAKEFLAGS="-j $(nproc) --keep-going" ./kresd_run.sh
  tags:
    - docker
    - linux
    - amd64

# sanity check that Unbound under Deckard still works
# I've selected the only tests which are working
# on kresd and Unbound 1.5.8 as well as 1.6.0
test:python3:sanity:unbound:
  image: cznic/deckard-ci
  stage: test
  script:
    - export PYTHON=python3
    - TESTS=sets/resolver/iter_hint_lame.rpl ./unbound_run.sh
    - TESTS=sets/resolver/iter_lame_root.rpl ./unbound_run.sh
    # these do not work with Unbound 1.5.8 which is in CI container
      #- TESTS=sets/resolver/nsec_wildcard_answer_response.rpl ./unbound_run.sh
      #- TESTS=sets/resolver/world_cz_lidovky_www.rpl ./unbound_run.sh
  tags:
    - docker
    - linux
    - amd64

# sanity check that PowerDNS recursor under Deckard still works
# I've selected couple tests which are working
# on kresd and PowerDNS recursor 4.0.0~alpha2 as well as 4.0.4
test:python3:sanity:pdnsrecursor:
  image: cznic/deckard-ci
  stage: test
  script:
    - export PYTHON=python3
    - TESTS=sets/resolver/iter_recurse.rpl ./pdns_run.sh
    - TESTS=sets/resolver/iter_tcbit.rpl ./pdns_run.sh
  tags:
    - docker
    - linux
    - amd64
