image: $CI_REGISTRY/knot/knot-resolver/ci:debian-stable
variables:
  LC_ALL: C.UTF-8


# Run all tests on the latest kresd version to ensure that we not push tests
# which do not work on latest kresd. It would lead to breakage in kresd CI.
test:latest:kresd:
  stage: test
  script:
    - git clone --depth=1 https://gitlab.labs.nic.cz/knot/knot-resolver.git kresd-local-build
    - GIT_DIR=$(pwd)/kresd-local-build/.git git log -1
    - ( cd kresd-local-build ; git submodule update --init --recursive )
    - PREFIX=$(pwd)/.local make -C kresd-local-build -k all
    - PREFIX=$(pwd)/.local make -C kresd-local-build install
    - TMPDIR=$(pwd) LD_LIBRARY_PATH=$(pwd)/.local/lib PATH=$(pwd)/.local/sbin:$PATH ./kresd_run.sh 
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
      - tmpdeckard*
  tags:
    - docker
    - linux
    - amd64

