FROM ubuntu

RUN apt-get update && apt-get install -y \
python3 \
python3-pip \
tcpdump \
sudo \
firefox \
xvfb \
tcpdump \
dnsutils \
sudo \
bind9 \
bind9utils \
bind9-doc

RUN pip3 install selenium xvfbwrapper

